Models/Cerveza.cs
using System;
using System.Collections.Generic;

namespace introAsp.Models
{
    public partial class Cerveza
    {
        public int Id { get; set; }
        public string Nombre { get; set; } = null!;
        public int Marca { get; set; }

        public virtual Marca MarcaNavigation { get; set; } = null!;
    }
}

Models/ErrorViewModel.cs
namespace introAsp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Marca.cs
using System;
using System.Collections.Generic;

namespace introAsp.Models
{
    public partial class Marca
    {
        public Marca()
        {
            Cervezas = new HashSet<Cerveza>();
        }

        public int Id { get; set; }
        public string Marca1 { get; set; } = null!;

        public virtual ICollection<Cerveza> Cervezas { get; set; }
    }
}

Models/ViewModels/CervezaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace introAsp.Models.ViewModels
{
    public class CervezaViewModel
    {
        [Required]
        public string Nombre { get; set; }
        [Required]
        public int Marca { get; set; }
        
    }
}

Models/tareaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace introAsp.Models
{
    public partial class tareaContext : DbContext
    {
        public tareaContext()
        {
        }

        public tareaContext(DbContextOptions<tareaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cerveza> Cervezas { get; set; } = null!;
        public virtual DbSet<Marca> Marcas { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Server=LAPTOP-QBLTU8QO\\SQLEXPRESS;Database=tarea; Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cerveza>(entity =>
            {
                entity.ToTable("cerveza");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Marca).HasColumnName("marca");

                entity.Property(e => e.Nombre)
                    .HasMaxLength(10)
                    .HasColumnName("nombre")
                    .IsFixedLength();

                entity.HasOne(d => d.MarcaNavigation)
                    .WithMany(p => p.Cervezas)
                    .HasForeignKey(d => d.Marca)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_cerveza_marca");
            });

            modelBuilder.Entity<Marca>(entity =>
            {
                entity.ToTable("marca");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Marca1)
                    .HasMaxLength(20)
                    .HasColumnName("marca")
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Controllers/CervezaController.cs
using introAsp.Models;
using introAsp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace introAsp.Controllers
{
    public class CervezaController : Controller
    {
        private readonly tareaContext _context;

        public CervezaController(tareaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cervezas =_context.Cervezas.Include( m=>m.MarcaNavigation );
            return View(await cervezas.ToListAsync());
        }

        public IActionResult create()
        {
            ViewData["Marcas"] = new SelectList(_context.Marcas, "Id", "Marca1");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> create(CervezaViewModel model)
        {
            if ( ModelState.IsValid )
            {
                var cerveza = new Cerveza()
                {
                    Nombre=model.Nombre,
                    Marca = model.Marca
                };
                _context.Add(cerveza);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }


           
            return View(model);
        }

    }
}

Controllers/HomeController.cs
using introAsp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace introAsp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MarcaController.cs
using introAsp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.X509Certificates;

namespace introAsp.Controllers
{
    public class MarcaController : Controller
    {

        private readonly tareaContext _context;

        public MarcaController(tareaContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {

            return View(await _context.Marcas.ToListAsync());
        }
    }
}

Views/Cerveza/Index.cshtml
@model List<Cerveza>

    <h1>Cervezas</h1>
    <p>
        <a asp-action="create" >Crear</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Marca</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var cerveza in Model){
                <tr>
                    <td>@Html.DisplayFor(m=>cerveza.Nombre)</td>
                    <td>@Html.DisplayFor(m=>cerveza.MarcaNavigation.Marca1)</td>
                </tr>
            }
        </tbody>
    </table>

Views/Cerveza/create.cshtml
@using introAsp.Models.ViewModels
@model CervezaViewModel

<h1>Crear cerveza</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" >
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <select asp-for="Marca" class="form-control" asp-items="ViewBag.Marcas" ></select>
                <span asp-validation-for="Marca" class="text-danger" ></span>
            </div>
            <div class="form-group">
               <input type="submit" value="Crear" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Marca/Index.cshtml
@model List<Marca>

    <h1>Marcas</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var marca in Model){
                <tr>
                    <td>@Html.DisplayFor(m=>marca.Marca1 )</td>
                </tr>
            }
        </tbody>
        
    </table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - introAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/introAsp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">introAsp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cerveza" asp-action="Index">Cervezas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - introAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>